[package]
name = "secs"
version = "0.0.1"
description = "Syntactic ECS"
keywords = ["gamedev"]
license = "Apache-2.0"
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[lib]
name = "secs"
path = "lib.rs"
plugin = true
crate-type = [ "dylib" ]
